### ISSUE TITLE
Critical threshold

### ISSUE THREAD

**Issue by haytxy** [githubDante/ethMon#1]
hello,

is there a possiblity to set a threshold beloow the exatct number?

Marcin

**Comment by githubDante** [comment]
The thresholds are controlled through the template/conf file. The value provided in the README is just an example. The threshold can be set to any value.

**Comment by haytxy** [comment]
hello, could you give an example of how to set the range? If I am using for example "10:30" then receive an error. 
![image](https://user-images.githubusercontent.com/79607995/121067154-002a6900-c7cb-11eb-8dfa-2d935769495f.png)

I'm referring to https://icinga.com/docs/icinga-2/latest/doc/05-service-monitoring/#threshold-ranges

Marcin

**Comment by githubDante** [comment]
Ranges are currently not supported, but will be added soon. See #2
